### ISSUE TITLE
Null Pointer at BasicAnnotator.java

### ISSUE THREAD

**Issue by jrgaston-hib** [SIMPATICOProject/simpatico-adaptation-engines#9]
I just deployed last version but there is an error at this line:

java.lang.NullPointerException	at eu.simpaticoproject.adaptation.text.spanish.BasicAnnotator.annotate(BasicAnnotator.java:56)

**Comment by ziorufus** [comment]
Can you send me the list of actions you performed? Did you set the posModel and lemmaModel properties properly?

**Comment by ziorufus** [comment]
Try to uncomment the two lines in `simpatico-default.props` and run the system again.

**Comment by smendez-hi** [comment]
Those lines are not commented. Here goes the spanish configuration:
```
es.annotators = spanish, readability, lexsimp
es.spanish.posModel = /home/simpatico/SIMPATICO/simpatico-adaptation-engines/es-pos-perceptron-autodict01-ancora-2.0.bin
es.spanish.lemmaModel = /home/simpatico/SIMPATICO/simpatico-adaptation-engines/es-lemma-perceptron-ancora-2.0.bin
es.readability.language = es
es.lsimp.host = localhost
es.lsimp.port = 1414
es.lsimp.language = es
es.lsimp.min_difficult = 4
es.customAnnotatorClass.lexsimp = eu.simpaticoproject.adaptation.text.tae.LexSimpAnnotator
```

**Comment by ziorufus** [comment]
Can you check that the two files exist in that location? (trivial)
Then, can you try to run the system without the `lexsimp` annotator? (just leave `es.annotators = spanish, readability`)?

**Comment by smendez-hi** [comment]
The files exist.
Trying without `lexsimp` gives the same error but also another one:
`java.io.FileNotFoundException: src/main/resources/es-pos-perceptron-autodict01-ancora-2.0.bin (No such file or directory)`
But in the config file the paths are changed to the location i put before, not to `src/main/resources`

**Comment by ziorufus** [comment]
Are you sure that the system is using the correct configuration file? How are you launching it?

**Comment by smendez-hi** [comment]
`java -jar target/simpatico-adaptation-engines-0.0.1-SNAPSHOT.jar`
Before removing `lexsimp` that error didn't appear. Probably is not related but anyway.

**Comment by ziorufus** [comment]
Can you try to run the `java` command adding `-Dconfig.file={CONFIG-FILE}`?

**Comment by smendez-hi** [comment]
With that it works. Thanks.
I can see an error in the logs but it doesn't affect the result: `java.io.IOException: Deprecated encoder keys in metadata. Use fsa.dict.encoder=SUFFIX`

Still no simplifications in the IFE component, but i don't know if that is an issue with this component...

**Comment by ziorufus** [comment]
That error is normal (sic!). It's a deprecated library used by the included linguistic tools (not written by me).
Regarding the simplifications, did you add back the `lexsimp` annotator?

**Comment by smendez-hi** [comment]
I forgot about that. Now added and every request i see in the logs:
`(E) Connection refused (Connection refused)  [http-nio-8081-exec-7 e.s.a.t.t.LexSimpAnnotator]`

But Lexical server is up and running.

**Comment by ziorufus** [comment]
Ok, now there is a connection error. Probably you should replace `lsimp` with `lexsimp`.

**Comment by smendez-hi** [comment]
I added `lexsimp`, not `lsimp`

**Comment by ziorufus** [comment]
Yes.

**Comment by smendez-hi** [comment]
Perfect, now it is working correctly. Thanks for your help!
